// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: pb/professional.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProfessionalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Profession    string                 `protobuf:"bytes,2,opt,name=profession,proto3" json:"profession,omitempty"`
	Contact       string                 `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfessionalRequest) Reset() {
	*x = CreateProfessionalRequest{}
	mi := &file_pb_professional_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfessionalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfessionalRequest) ProtoMessage() {}

func (x *CreateProfessionalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_professional_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfessionalRequest.ProtoReflect.Descriptor instead.
func (*CreateProfessionalRequest) Descriptor() ([]byte, []int) {
	return file_pb_professional_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProfessionalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProfessionalRequest) GetProfession() string {
	if x != nil {
		return x.Profession
	}
	return ""
}

func (x *CreateProfessionalRequest) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type CreateProfessionalResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ProfessionalId uint32                 `protobuf:"varint,3,opt,name=professional_id,json=professionalId,proto3" json:"professional_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProfessionalResponse) Reset() {
	*x = CreateProfessionalResponse{}
	mi := &file_pb_professional_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfessionalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfessionalResponse) ProtoMessage() {}

func (x *CreateProfessionalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_professional_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfessionalResponse.ProtoReflect.Descriptor instead.
func (*CreateProfessionalResponse) Descriptor() ([]byte, []int) {
	return file_pb_professional_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfessionalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateProfessionalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateProfessionalResponse) GetProfessionalId() uint32 {
	if x != nil {
		return x.ProfessionalId
	}
	return 0
}

type GetProfessionalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfessionalRequest) Reset() {
	*x = GetProfessionalRequest{}
	mi := &file_pb_professional_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfessionalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfessionalRequest) ProtoMessage() {}

func (x *GetProfessionalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_professional_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfessionalRequest.ProtoReflect.Descriptor instead.
func (*GetProfessionalRequest) Descriptor() ([]byte, []int) {
	return file_pb_professional_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfessionalRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Professional struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Profession    string                 `protobuf:"bytes,3,opt,name=profession,proto3" json:"profession,omitempty"`
	Contact       string                 `protobuf:"bytes,4,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Professional) Reset() {
	*x = Professional{}
	mi := &file_pb_professional_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Professional) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Professional) ProtoMessage() {}

func (x *Professional) ProtoReflect() protoreflect.Message {
	mi := &file_pb_professional_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Professional.ProtoReflect.Descriptor instead.
func (*Professional) Descriptor() ([]byte, []int) {
	return file_pb_professional_proto_rawDescGZIP(), []int{3}
}

func (x *Professional) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Professional) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Professional) GetProfession() string {
	if x != nil {
		return x.Profession
	}
	return ""
}

func (x *Professional) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type GetProfessionalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Professional  *Professional          `protobuf:"bytes,1,opt,name=professional,proto3" json:"professional,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfessionalResponse) Reset() {
	*x = GetProfessionalResponse{}
	mi := &file_pb_professional_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfessionalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfessionalResponse) ProtoMessage() {}

func (x *GetProfessionalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_professional_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfessionalResponse.ProtoReflect.Descriptor instead.
func (*GetProfessionalResponse) Descriptor() ([]byte, []int) {
	return file_pb_professional_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfessionalResponse) GetProfessional() *Professional {
	if x != nil {
		return x.Professional
	}
	return nil
}

func (x *GetProfessionalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListProfessionalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfessionalsRequest) Reset() {
	*x = ListProfessionalsRequest{}
	mi := &file_pb_professional_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfessionalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfessionalsRequest) ProtoMessage() {}

func (x *ListProfessionalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_professional_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfessionalsRequest.ProtoReflect.Descriptor instead.
func (*ListProfessionalsRequest) Descriptor() ([]byte, []int) {
	return file_pb_professional_proto_rawDescGZIP(), []int{5}
}

type ListProfessionalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Professionals []*Professional        `protobuf:"bytes,1,rep,name=professionals,proto3" json:"professionals,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfessionalsResponse) Reset() {
	*x = ListProfessionalsResponse{}
	mi := &file_pb_professional_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfessionalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfessionalsResponse) ProtoMessage() {}

func (x *ListProfessionalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_professional_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfessionalsResponse.ProtoReflect.Descriptor instead.
func (*ListProfessionalsResponse) Descriptor() ([]byte, []int) {
	return file_pb_professional_proto_rawDescGZIP(), []int{6}
}

func (x *ListProfessionalsResponse) GetProfessionals() []*Professional {
	if x != nil {
		return x.Professionals
	}
	return nil
}

func (x *ListProfessionalsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pb_professional_proto protoreflect.FileDescriptor

var file_pb_professional_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x69, 0x0a, 0x19, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x22, 0x79, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x66,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49,
	0x64, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6c, 0x0a, 0x0c, 0x50,
	0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x22, 0x69, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x0c, 0x70, 0x72,
	0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x66,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x6d, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a,
	0x0d, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32,
	0x88, 0x02, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x1d, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12,
	0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x73, 0x12, 0x1c, 0x2e,
	0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x70, 0x73, 0x61, 0x6c, 0x64, 0x61,
	0x6e, 0x61, 0x2f, 0x67, 0x6f, 0x2d, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x2d, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pb_professional_proto_rawDescOnce sync.Once
	file_pb_professional_proto_rawDescData []byte
)

func file_pb_professional_proto_rawDescGZIP() []byte {
	file_pb_professional_proto_rawDescOnce.Do(func() {
		file_pb_professional_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_professional_proto_rawDesc), len(file_pb_professional_proto_rawDesc)))
	})
	return file_pb_professional_proto_rawDescData
}

var file_pb_professional_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_professional_proto_goTypes = []any{
	(*CreateProfessionalRequest)(nil),  // 0: pb.CreateProfessionalRequest
	(*CreateProfessionalResponse)(nil), // 1: pb.CreateProfessionalResponse
	(*GetProfessionalRequest)(nil),     // 2: pb.GetProfessionalRequest
	(*Professional)(nil),               // 3: pb.Professional
	(*GetProfessionalResponse)(nil),    // 4: pb.GetProfessionalResponse
	(*ListProfessionalsRequest)(nil),   // 5: pb.ListProfessionalsRequest
	(*ListProfessionalsResponse)(nil),  // 6: pb.ListProfessionalsResponse
}
var file_pb_professional_proto_depIdxs = []int32{
	3, // 0: pb.GetProfessionalResponse.professional:type_name -> pb.Professional
	3, // 1: pb.ListProfessionalsResponse.professionals:type_name -> pb.Professional
	0, // 2: pb.ProfessionalService.CreateProfessional:input_type -> pb.CreateProfessionalRequest
	2, // 3: pb.ProfessionalService.GetProfessional:input_type -> pb.GetProfessionalRequest
	5, // 4: pb.ProfessionalService.ListProfessionals:input_type -> pb.ListProfessionalsRequest
	1, // 5: pb.ProfessionalService.CreateProfessional:output_type -> pb.CreateProfessionalResponse
	4, // 6: pb.ProfessionalService.GetProfessional:output_type -> pb.GetProfessionalResponse
	6, // 7: pb.ProfessionalService.ListProfessionals:output_type -> pb.ListProfessionalsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_professional_proto_init() }
func file_pb_professional_proto_init() {
	if File_pb_professional_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_professional_proto_rawDesc), len(file_pb_professional_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_professional_proto_goTypes,
		DependencyIndexes: file_pb_professional_proto_depIdxs,
		MessageInfos:      file_pb_professional_proto_msgTypes,
	}.Build()
	File_pb_professional_proto = out.File
	file_pb_professional_proto_goTypes = nil
	file_pb_professional_proto_depIdxs = nil
}
